name: Deploy With Docker
on: push
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Display Connected
          run: echo "Connect Successful..."

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
              push: true
              tags: user/app:latest